---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 5b3bea203964a9cfd54ec1dc89c1679601a59869
    app.quarkus.io/build-timestamp: 2021-07-01 - 01:24:45 +0000
  labels:
    app.kubernetes.io/name: openshift-quarkus-ab
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: openshift-quarkus-ab
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: openshift-quarkus-ab
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 5b3bea203964a9cfd54ec1dc89c1679601a59869
    app.quarkus.io/build-timestamp: 2021-07-01 - 01:24:45 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: openshift-quarkus-ab
  name: openshift-quarkus-ab
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: openshift-quarkus-ab
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 5b3bea203964a9cfd54ec1dc89c1679601a59869
        app.quarkus.io/build-timestamp: 2021-07-01 - 01:24:45 +0000
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: openshift-quarkus-ab
    spec:
      containers:
        - args:
            - -Dquarkus.http.host=0.0.0.0
            - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
            - -jar
            - /deployments/quarkus-run.jar
          command:
            - java
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: rmarques/openshift-quarkus-ab:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: openshift-quarkus-ab
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
