---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 0f412736fd026e7847a7b00331c0019411cf018e
    app.quarkus.io/build-timestamp: 2021-07-01 - 01:54:05 +0000
  labels:
    app.kubernetes.io/name: openshift-quarkus-ab
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: openshift-quarkus-ab
  namespace: quarkus-ab
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: openshift-quarkus-ab
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: openjdk-11
  namespace: quarkus-ab
spec:
  dockerImageRepository: registry.access.redhat.com/ubi8/openjdk-11
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 0f412736fd026e7847a7b00331c0019411cf018e
    app.quarkus.io/build-timestamp: 2021-07-01 - 01:54:05 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: openshift-quarkus-ab
    app.openshift.io/runtime: quarkus
  name: openshift-quarkus-ab
  namespace: quarkus-ab
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 0f412736fd026e7847a7b00331c0019411cf018e
    app.quarkus.io/build-timestamp: 2021-07-01 - 01:54:05 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: openshift-quarkus-ab
    app.openshift.io/runtime: quarkus
  name: openshift-quarkus-ab
  namespace: quarkus-ab
spec:
  output:
    to:
      kind: ImageStreamTag
      name: openshift-quarkus-ab:1.0.0-SNAPSHOT
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-11:latest
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 0f412736fd026e7847a7b00331c0019411cf018e
    app.quarkus.io/build-timestamp: 2021-07-01 - 01:54:05 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: openshift-quarkus-ab
    app.openshift.io/runtime: quarkus
  name: openshift-quarkus-ab
  namespace: quarkus-ab
spec:
  replicas: 1
  selector:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: openshift-quarkus-ab
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/commit-id: 0f412736fd026e7847a7b00331c0019411cf018e
        app.quarkus.io/build-timestamp: 2021-07-01 - 01:54:05 +0000
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: openshift-quarkus-ab
        app.openshift.io/runtime: quarkus
      namespace: quarkus-ab
    spec:
      containers:
        - args:
            - -Dquarkus.http.host=0.0.0.0
            - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
            - -jar
            - /deployments/quarkus-run.jar
          command:
            - java
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/openshift-quarkus-ab-1.0.0-SNAPSHOT-runner.jar
          image: rmarques/openshift-quarkus-ab:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: openshift-quarkus-ab
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - openshift-quarkus-ab
        from:
          kind: ImageStreamTag
          name: openshift-quarkus-ab:1.0.0-SNAPSHOT
      type: ImageChange
